### PR TITLE
Added clear button

### PR DESCRIPTION
**Pull request by heyyayesh**
Added a "Clear" button below the inputs that clears both the inputs and sets the amounts to 0 so that the converter is ready for next conversion. Hope this comes in handy.

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
@heyyayesh you did very well

**Comment by heyyayesh** [comment]
> @heyyayesh you did very well

Thanks! I also wanted to refactor the code to have proper indentation and possibly add some more styling to the page. I might get back to that once I have the time. If you want me to create an issue, please let me know.

**Comment by codemaniac-sahil** [comment]
I already created the issue on UI/UX of website please check.

**Comment by codemaniac-sahil** [comment]
If you can fix this issue

**Comment by heyyayesh** [comment]
Great! I will get back to it as soon as I can.

**Pull request merged**
