### PR TITLE
Added country flag [fixes #6]

### LINKED ISSUE #6: Add country flag
Add country flag in the input section like this https://www.xe.com/currencyconverter/convert/?Amount=1&From=EUR&To=GBP

### PR DESCRIPTION
**Pull request by najeebkp**
#### Added country flag into the currency selector.

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
Screenshot (24)
It is not showing flags of country

**Comment by najeebkp** [comment]
Screenshot from 2022-10-02 16-21-27

Its showing fine !

**Comment by codemaniac-sahil** [comment]
But why it is not showing on my side.

**Comment by codemaniac-sahil** [comment]
Screenshot (25)
It does not able to fetch the flag

**Comment by najeebkp** [comment]
can you hard refresh ? which browser are you using?

**Comment by codemaniac-sahil** [comment]
Google chrome

**Comment by najeebkp** [comment]
No need to fetch any flags from outside. its a separate component -( hard coded)

**Comment by codemaniac-sahil** [comment]
> No need to fetch any flags from outside. its a separate component -( hard coded)

okay but why it is not working from my side

**Comment by codemaniac-sahil** [comment]
Screenshot (26)
It is not working on brave browser either

**Comment by najeebkp** [comment]
No Idea. Check with other operating systems.

**Comment by codemaniac-sahil** [comment]
It will be good if you use api for fetching the countries flag

**Comment by codemaniac-sahil** [comment]
Screenshot (27)
It only showing KID's flag

**Comment by najeebkp** [comment]
Its windows issue. they are not supporting flags emojis.
https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05?page=1

**Comment by codemaniac-sahil** [comment]
Please fix this

**Comment by codemaniac-sahil** [comment]
Try to use API

**Comment by najeebkp** [comment]
Let me check !

**Comment by najeebkp** [comment]
I'm sorry brother. i couldn't find a solution.

**Comment by codemaniac-sahil** [comment]
Don't worry, it happens

**Comment by codemaniac-sahil** [comment]
@najeebkp you can use this api to fetch country flag 
https://ipapi.com/documentation

**Pull request closed without merging**
